# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence
# whose values do not exceed four million,
# find the sum of the even-valued terms.
#start with 1 and 2
a1 = 1
a2 = 2
sum = 2;
until  a2 > 4e6
	a3 = a2 + a1;
	a1 = a2
	a2 = a3
	break if a2 > 4e6
	if(a2 % 2 == 0)
		sum = sum + a2
	end
	#show Fibonacci
	# puts b
end
puts "sum = #{sum}"