=begin 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end
#Find the divisor of the number n
def find_divisors(n)
	sum_div = 2
  (2..Math.sqrt(n).to_i).each do |i|
  	if n % i == 0
  		sum_div += 2
  	end
  end
  return sum_div
end

def find_first_triangle(n)
  next_number = 3 #number position
  first_triagle = 3 #start 1 3
  while find_divisors(first_triagle) < n
  	first_triagle += next_number
  	next_number += 1
  end
  return first_triagle
end

puts find_first_triangle(500)
  
 
